//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company : Account
    {
        public Company()
        {
            this.Shares = new HashSet<Share>();
        }
    
        public long PersonalDetailId { get; set; }
    
        public virtual PersonalDetail PersonalDetail { get; set; }
        public virtual ICollection<Share> Shares { get; set; }
    }
}
